"""init_db

Revision ID: 7c9d5c20bbd3
Revises:
Create Date: 2025-11-23 22:45:17.741021

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7c9d5c20bbd3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favorite_teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_team_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_favorite_teams_api_team_id"), "favorite_teams", ["api_team_id"], unique=True)
    op.create_index(op.f("ix_favorite_teams_id"), "favorite_teams", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_favorite_teams_id"), table_name="favorite_teams")
    op.drop_index(op.f("ix_favorite_teams_api_team_id"), table_name="favorite_teams")
    op.drop_table("favorite_teams")
    # ### end Alembic commands ###
